'use strict';

const CJK = '\\u3000-\\u30ff\\u3400-\\u4dbf\\u4e00-\\u9fff\\uf900-\\ufaff\\uff00-\\uffef';
const CJK_THEN_SPACE = new RegExp(`([${CJK}])[ \\t]+(?=[${CJK}0-9])`, 'g');
const DIGIT_THEN_SPACE = new RegExp(`([0-9])[ \\t]+(?=[${CJK}])`, 'g');

// Tesseract's Japanese model inserts spaces between characters
// ("本 日 20 時"). Remove spaces that touch CJK text, keep them between
// Latin words.
function cleanOcrText(text) {
  if (!text) return '';
  return String(text)
    .replace(/\r\n?/g, '\n')
    .replace(CJK_THEN_SPACE, '$1')
    .replace(DIGIT_THEN_SPACE, '$1')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

const URL_RE = /^(https?:\/\/|www\.)[^\s]+$/i;
function isUrl(text) {
  if (!text) return false;
  const t = String(text).trim();
  return t.length < 4096 && !t.includes('\n') && URL_RE.test(t);
}

function previewOf(text, max = 400) {
  if (!text) return '';
  const t = String(text);
  return t.length > max ? t.slice(0, max) + '…' : t;
}

// Clipboard formats apps use to mark content (nspasteboard.org convention on
// macOS, Windows' clipboard-history opt-out formats).
//   confidential: passwords etc. (Paste: 「機密情報を無視する」)
//   transient:    temporary / auto-generated data (「一時的なコンテンツを無視する」)
const CONFIDENTIAL_FORMATS = [
  'org.nspasteboard.ConcealedType',
  'com.agilebits.onepassword',
  'ExcludeClipboardContentFromMonitorProcessing',
  'Clipboard Viewer Ignore'
];
const TRANSIENT_FORMATS = [
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'de.petermaurer.TransientPasteboardType',
  'com.typeit4me.clipping',
  'Pasteboard generator type'
];
const SENSITIVE_FORMATS = [...CONFIDENTIAL_FORMATS, ...TRANSIENT_FORMATS];

function rawFormat(name) {
  return `electron application/osclipboard;format="${name}"`;
}

function isExcludedApp(source, patterns) {
  if (!source || !Array.isArray(patterns)) return false;
  const hay = `${source.name || ''} ${source.bundleId || ''}`.toLowerCase();
  if (!hay.trim()) return false;
  return patterns.some((p) => {
    const needle = String(p || '').trim().toLowerCase();
    return needle && hay.includes(needle);
  });
}

function formatBytes(n) {
  if (!Number.isFinite(n)) return '';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

// Text shown on a card footer, Paste-style.
function textStats(text) {
  const t = String(text || '');
  const chars = Array.from(t).length;
  const lines = t ? t.split(/\r?\n/).length : 0;
  return { chars, lines };
}

// Links that look like one-time / signed URLs are never fetched for previews.
function isSafeForLinkPreview(url) {
  try {
    const u = new URL(url);
    if (!/^https?:$/.test(u.protocol)) return false;
    if (u.username || u.password) return false;
    const host = u.hostname.replace(/^\[|\]$/g, '');
    if (/^(localhost|127\.|10\.|0\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|169\.254\.|100\.(6[4-9]|[7-9]\d|1[01]\d|12[0-7])\.)/i.test(host)) return false;
    if (host.includes(':')) return false; // IPv6 literals (::1, fe80::, fc00::…)
    if (!host.includes('.')) return false; // intranet single-label names
    if (/\.(local|internal|lan|corp|home|intranet)$/i.test(host)) return false;
    const risky = /(token|code|key|sig|signature|auth|session|otp|password|passwd|secret|ticket|magic|invite|verify|reset|confirm|login)/i;
    for (const k of u.searchParams.keys()) if (risky.test(k)) return false;
    if (/(reset|verify|confirm|magic|unsubscribe|logout|signin|login|activate)/i.test(u.pathname)) return false;
    return true;
  } catch {
    return false;
  }
}

module.exports = {
  cleanOcrText, isUrl, previewOf, SENSITIVE_FORMATS, CONFIDENTIAL_FORMATS, TRANSIENT_FORMATS, rawFormat,
  isExcludedApp, formatBytes, textStats, isSafeForLinkPreview
};
